name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  check-general-crates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cargo check
        run: cargo check -p aranya-embedded-config -p aranya-embedded-storage-dumper -p envelope-ffi -p parameter-store

  check-leaf-crates:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate:
          - chat-app
          - demo-esp32-s3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install esp toolchain
        run: |
            sudo apt-get update
            sudo apt-get install libudev-dev --fix-missing
            cargo install espup --locked
            espup install
            . /home/runner/export-esp.sh

      - name: Check default features
        working-directory: "crates/${{ matrix.crate }}"
        run: |
          cargo check

      - name: Check different boards
        working-directory: "crates/${{ matrix.crate }}"
        run: |
          cargo check --no-default-features --features net-esp-now,storage-internal --features adafruit-feather-s3
          cargo check --no-default-features --features net-esp-now,storage-internal --features adafruit-qtpy-s3

      - name: Check different storage
        working-directory: "crates/${{ matrix.crate }}"
        run: |
          cargo check --no-default-features --features spideroak-demo-v2,net-esp-now --features storage-sd

      - name: Check different network drivers
        working-directory: "crates/${{ matrix.crate }}"
        run: |
          cargo check --no-default-features --features spideroak-demo-v2,storage-internal --features net-irda
