name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  check-general-crates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cargo check
        run: cargo check -p aranya-embedded-config -p aranya-embedded-storage-dumper -p envelope-ffi -p parameter-store

  check-leaf-crates:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate:
          - chat-app
          - demo-esp32-s3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install espup
        uses: aranya-project/install-action@main
        with:
          tool: espup@0.16.0

      - name: Install esp toolchain
        run: espup install

      - name: Check default features
        working-directory: "crates/${{ matrix.crate }}"
        run: |
          cargo check

      - name: Check boards
        working-directory: "crates/${{ matrix.crate }}"
        run: |
          cargo check --no-default-features --features net-esp-now,storage-internal --features adafruit-feather-s3
          cargo check --no-default-features --features net-esp-now,storage-internal --features adafruit-qtpy-s3

      - name: Check storage and net combos
        working-directory: "crates/${{ matrix.crate }}"
        run: |
          cargo check --no-default-features --features spideroak-demo-v2 --features storage-internal,net-irda
          cargo check --no-default-features --features spideroak-demo-v2 --features storage-sd,net-irda
          # TODO: Fix duplicate timer usage
          # cargo check --no-default-features --features spideroak-demo-v2 --features storage-sd,net-esp-now
